#
# base-parent (https://github.com/hazendaz/base-parent)
#
# Copyright 2011-2020 Hazendaz.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of The Apache Software License,
# Version 2.0 which accompanies this distribution, and is available at
# https://www.apache.org/licenses/LICENSE-2.0.txt
#
# Contributors:
#     Hazendaz (Jeremy Landis).
#

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.sun.xml.ws:jaxws-maven-plugin
    versions:
    - ">= 3.0.0"
  - dependency-name: org.hibernate.validator:hibernate-validator-annotation-processor
    versions:
    - ">= 7.0.0"
  - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
    versions:
    - ">= 3.0.0"
