# SPDX-License-Identifier: Apache-2.0
# See LICENSE file for details.
#
# Copyright 2011-2026 Hazendaz

invoker.goals = site
invoker.userPropertiesFile = user.properties
invoker.buildResult = success
